import { stripVTControlCharacters } from "node:util";
import {
	AssistantMessageComponent,
	BashExecutionComponent,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomMessageComponent,
	ToolExecutionComponent,
	UserMessageComponent,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLsToolDefinition,
	createPowerShellToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	getMarkdownTheme,
	sessionEntryToContextMessages,
	type SessionEntry,
} from "@earendil-works/pi-coding-agent";
import { Text, type Component, type TUI } from "@earendil-works/pi-tui";

type SessionMessage = Extract<SessionEntry, { type: "message" }>["message"];
type ContentBlock = Exclude<Extract<SessionMessage, { content: unknown }>["content"], string>[number];

interface TranscriptOptions {
	width: number;
	cwd: string;
	ui: TUI;
	hideThinking: boolean;
	outputPad?: 0 | 1;
	codeBlockIndent?: string;
}

function plainText(text: string): string {
	return stripVTControlCharacters(text)
		.replace(/\r\n?/g, "\n")
		.replace(/\t/g, "    ")
		.replace(/[\x00-\x08\x0b-\x1f\x7f-\x9f]/g, "");
}

function sanitizeValue<T>(value: T): T {
	if (typeof value === "string") return plainText(value) as T;
	if (Array.isArray(value)) return value.map(sanitizeValue) as T;
	if (value && typeof value === "object") {
		return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, sanitizeValue(item)])) as T;
	}
	return value;
}

function prepareMessage(message: SessionMessage, hideThinking: boolean): SessionMessage {
	if (!("content" in message) || !Array.isArray(message.content)) return sanitizeValue(message);

	// Remove image payloads and replay signatures before handing content to renderers.
	const content = (message.content as ContentBlock[]).flatMap<ContentBlock>((block) => {
		switch (block.type) {
			case "text":
				return [{ type: "text", text: block.text }];
			case "image":
				return [{ type: "text", text: `[Image: ${block.mimeType}]` }];
			case "thinking":
				return hideThinking ? [] : [{ type: "thinking", thinking: block.thinking || "[Redacted]" }];
			case "toolCall":
				return [{ type: "toolCall", id: block.id, name: block.name, arguments: block.arguments }];
		}
	});
	return sanitizeValue({ ...message, content }) as SessionMessage;
}

function safeStyledLine(line: string): string {
	// Keep only SGR colour/style sequences generated by Pi. Drop OSC links, prompt marks,
	// clipboard commands, cursor movement, and other terminal controls.
	return line.split(/(\x1b\[[0-9;:]*m)/g)
		.map((part) => /^\x1b\[[0-9;:]*m$/.test(part) ? part : plainText(part))
		.join("") + "\x1b[0m";
}

export function formatTranscript(branch: readonly SessionEntry[], options: TranscriptOptions): string {
	if (!Number.isInteger(options.width) || options.width < 12) throw new Error("Conversation pane is too narrow");
	const markdownTheme = { ...getMarkdownTheme(), codeBlockIndent: options.codeBlockIndent ?? "  " };
	const outputPad = options.outputPad ?? 1;
	const tools = new Map([
		createReadToolDefinition(options.cwd), createBashToolDefinition(options.cwd),
		createPowerShellToolDefinition(options.cwd), createEditToolDefinition(options.cwd),
		createWriteToolDefinition(options.cwd), createGrepToolDefinition(options.cwd),
		createFindToolDefinition(options.cwd), createLsToolDefinition(options.cwd),
	].map((tool) => [tool.name, tool]));
	const components: Component[] = [];
	const pendingTools = new Map<string, ToolExecutionComponent>();

	const toolComponent = (name: string, id: string, args: unknown) => {
		const component = new ToolExecutionComponent(
			name, id, args, { showImages: false }, tools.get(name), options.ui, options.cwd,
		);
		// Do not call setArgsComplete(): edit previews would read today's files instead
		// of displaying the recorded diff. Expanded results use persisted details only.
		component.setExpanded(true);
		components.push(component);
		return component;
	};

	for (const entry of branch) {
		for (const original of sessionEntryToContextMessages(entry)) {
			if (original.role === "system" || (original.role === "custom" && !original.display)) continue;
			const message = prepareMessage(original, options.hideThinking);
			switch (message.role) {
				case "user": {
					const text = typeof message.content === "string" ? message.content
						: message.content.filter((block) => block.type === "text").map((block) => block.text).join("\n");
					components.push(new UserMessageComponent(text, markdownTheme, outputPad));
					break;
				}
				case "assistant":
					components.push(new AssistantMessageComponent(message, options.hideThinking, markdownTheme, undefined, outputPad));
					for (const block of message.content) {
						if (block.type !== "toolCall") continue;
						const component = toolComponent(block.name, block.id, block.arguments);
						if (message.stopReason === "aborted" || message.stopReason === "error") {
							component.updateResult({
								content: [{ type: "text", text: message.errorMessage || "Operation aborted" }], isError: true,
							});
						}
						pendingTools.set(block.id, component);
					}
					break;
				case "toolResult": {
					const component = pendingTools.get(message.toolCallId)
						?? toolComponent(message.toolName, message.toolCallId, {});
					component.updateResult(message);
					pendingTools.delete(message.toolCallId);
					break;
				}
				case "bashExecution": {
					const component = new BashExecutionComponent(message.command, options.ui, message.excludeFromContext);
					// Stop the component's loader immediately; this is a completed snapshot.
					component.setComplete(message.exitCode, message.cancelled, undefined, message.fullOutputPath);
					component.appendOutput(message.output);
					component.setExpanded(true);
					components.push(component);
					break;
				}
				case "custom":
					components.push(new CustomMessageComponent(message, undefined, markdownTheme, outputPad));
					break;
				case "branchSummary": {
					const component = new BranchSummaryMessageComponent(message, markdownTheme);
					component.setExpanded(true);
					components.push(component);
					break;
				}
				case "compactionSummary": {
					const component = new CompactionSummaryMessageComponent(message, markdownTheme);
					component.setExpanded(true);
					components.push(component);
					break;
				}
			}
		}
	}

	const header = new Text([
		"Pi conversation - active-branch history, not the exact model context.",
		"Includes older messages retained after compaction. Tool results are expanded.",
		"Snapshot: reopen after resizing to reflow. Images appear as placeholders.",
		"less: b = page up | ?text = search backward | G = bottom | q = close pager",
	].join("\n"), 1, 1);
	const lines = header.render(options.width);
	let messageLines = 0;
	for (const component of components) {
		const rendered = component.render(options.width);
		messageLines += rendered.length;
		for (const line of rendered) lines.push(line);
	}
	if (messageLines === 0) lines.push(...new Text("No conversation messages yet.", 1, 0).render(options.width));
	return lines.map(safeStyledLine).join("\n") + "\n";
}
