lastChangelogVersion: 14.2.1
modelRoles: 
  default: github-copilot/claude-sonnet-4.6:medium
  smol: github-copilot/claude-haiku-4.5
  commit: github-copilot/claude-haiku-4.5
  plan: github-copilot/gemini-3.1-pro-preview:high
  slow: github-copilot/gemini-3.1-pro-preview:high
  task: github-copilot/claude-sonnet-4.5:high
  designer: github-copilot/gemini-3.1-pro-preview:high
defaultThinkingLevel: medium
doubleEscapeAction: tree
bashInterceptor: 
  enabled: true
lsp: 
  formatOnWrite: false
task: 
  eager: true
  maxConcurrency: 5
  disabledAgents: 
    []
skills: 
  enabled: true
grep: 
  contextBefore: 3
  contextAfter: 3
browser: 
  enabled: false
stt: 
  enabled: false
ask: 
  notify: "on"
disabledProviders: 
  - opencode
disabledExtensions: 
  - skill:tech-digest
  - skill:oh-my-pi-history-ingest