lastChangelogVersion: 14.0.3
modelRoles: 
  default: github-copilot/claude-opus-4.5:high
  smol: github-copilot/claude-haiku-4.5
  commit: github-copilot/claude-haiku-4.5
  plan: github-copilot/claude-opus-4.5:high
  slow: github-copilot/claude-opus-4.5
  task: github-copilot/claude-sonnet-4.5:high
defaultThinkingLevel: medium
doubleEscapeAction: tree
bashInterceptor: 
  enabled: true
lsp: 
  formatOnWrite: false
task: 
  eager: true
  maxConcurrency: 5
  disabledAgents: 
    []
skills: 
  enabled: true
grep: 
  contextBefore: 3
  contextAfter: 3
browser: 
  enabled: false
stt: 
  enabled: false
ask: 
  notify: "on"
